server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    # 来表明自己是一个eureka server
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
